'use client';
import { upload } from '@vercel/blob/client';
import { FormEvent, useRef, useState } from 'react';
import Link from 'next/link';

type Image = { url: string; pathname: string };
export default function StudioClient({ mode, images = [], remove }: { mode: 'login' | 'manage'; images?: Image[]; remove?: (formData: FormData) => Promise<void> }) {
  const [message, setMessage] = useState(''); const input = useRef<HTMLInputElement>(null);
  async function login(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const password = new FormData(e.currentTarget).get('password'); const res = await fetch('/api/studio/login', { method: 'POST', headers: {'content-type':'application/json'}, body: JSON.stringify({ password }) }); if (res.ok) location.reload(); else setMessage('That password didn’t work.'); }
  async function addImages() { const files = input.current?.files; if (!files?.length) return; setMessage('Uploading…'); try { await Promise.all([...files].map(file => upload(`portfolio/${Date.now()}-${file.name}`, file, { access: 'public', handleUploadUrl: '/api/studio/upload' }))); location.reload(); } catch { setMessage('Upload failed — check your Blob store connection.'); } }
  if (mode === 'login') return <main className="studio login"><Link href="/" className="wordmark"><i />CHAI.TXT</Link><form onSubmit={login}><p className="kicker">Private route</p><h1>Studio access</h1><input name="password" type="password" placeholder="Your Studio password" required autoFocus/><button className="button" type="submit">Unlock →</button>{message && <small>{message}</small>}</form></main>;
  return <main className="studio"><nav><Link href="/" className="wordmark"><i />CHAI.TXT</Link><span className="kicker">Studio / image manager</span></nav><header><div><p className="kicker">Vercel Blob</p><h1>Upload the good stuff.</h1><p>These images are available in your public Blob library; copy a URL for a project page or use them in the site as we expand it.</p></div><div><input ref={input} onChange={addImages} type="file" accept="image/png,image/jpeg,image/webp,image/gif" multiple hidden/><button className="button" onClick={() => input.current?.click()}>Add images +</button><small>{message}</small></div></header>{!images.length && <p className="studio-note">Connect a Vercel Blob store and add its token to enable uploads. Your local build stays safe without it.</p>}<div className="image-grid">{images.map(image => <article key={image.url}><img src={image.url} alt="Uploaded portfolio asset"/><p>{image.pathname.replace('portfolio/','')}</p><div><button onClick={() => navigator.clipboard.writeText(image.url)}>Copy URL</button><form action={remove!}><input type="hidden" name="url" value={image.url}/><button>Delete</button></form></div></article>)}</div></main>;
}
