export const APP = 'https://akshara.chaii.wtf';
export const APPLY = 'https://akshara.chaii.wtf/?apply';
export const VERSION = '0.1.0-alpha.15';
const base = `https://github.com/cxaiiii/akshara-releases/releases/download/v${VERSION}`;
export const WIN = `${base}/Akshara-${VERSION}-win-x64-setup.exe`;
export const MAC = `${base}/Akshara-${VERSION}-mac-arm64.dmg`;
export const ANDROID = `${base}/Akshara-${VERSION}-android.apk`;
export const RELEASE = `https://github.com/cxaiiii/akshara-releases/releases/tag/v${VERSION}`;
export const ISSUES = 'https://github.com/cxaiiii/akshara-releases/issues';
